version: "3.8"
services:
  ixian-pool:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        URL: "https://github.com/ProjectIxian"
        BRANCH: "main"
        #SHA: ""
        DLT_URL: "http://ixian-dlt:8081"
    ports:
      - "444:443"
    expose:
      - "443"
      